### PR TITLE
[Merged by Bors] - [Async] Implement log streams with async/await

### PR DESCRIPTION
**Pull request by nlordell**
This PR implements log streams with async/await.

### Test Plan

CI - unit tests and examples are still using this code.

### CODE REVIEW

**Comment by nlordell** [comment]
bors try

**Review by bh2smith — APPROVED** [review]
Sweet! Looks like you managed to remove a bunch of boiler plate! I am "awaiting" merge!

**Review by e00E — APPROVED** [review]

**Comment by fleupold** [comment]
Why do you run bors try? Isn't the automatic CI on this PR enough? Or does it make it instant to merge if there are no more changes afterwards?

**Pull request closed without merging**
