### PR TITLE
Updates for rust v1.65

### PR DESCRIPTION
**Pull request by josojo**

### CODE REVIEW

**Review by nlordell — APPROVED** [review]
LGTM.

**Review by vkgnosis — APPROVED** [review]

**Comment by josojo** [comment]
Does anyone more familiar with the project know where the rust(1.56,false,false) CI task is configured? I can not find it.

**Comment by vkgnosis** [comment]
It is in the branch protection rules for the main branch. https://github.com/gnosis/ethcontract-rs/settings/branch_protection_rules/11837431 if this direct link works. I think we have to temporarily disable it, merge, make CI run on main, re-enable.

**Comment by nlordell** [comment]
Disabled the branch protection rules for 1.56.1. You might need to trick GitHub into re-running CI.

**Pull request merged**
