### PR TITLE
Fix missing Some in deployment transaction hash

### PR DESCRIPTION
**Pull request by vkgnosis**
Serves me right for not making sure that an example uses this.

### CODE REVIEW

**Review by fleupold — APPROVED** [review]
Does this mean 0.11.0 broken (or only if one tries to use the features)? Maybe we can then also include #464 in the next release to not cut too many minor versions (although it doesn't really matter).

**Comment by vkgnosis** [comment]
Only broken if the feature was used.

**Comment by vkgnosis** [comment]
We can release both together as 0.12.0. When your PR is ready, you or I can merge both, and bump the version.

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
I suggest bumping to `0.11.1`, but not a strong opinion either way.

**Pull request merged**
