### PR TITLE
Merge feature branch for hardhat support

### LINKED ISSUE #512: Add support for `hardhat` and `hardhat-deploy` artifacts and deployments.
Since we are migrating more and more of our repositories to `hardhat` and `hardhat-deploy`, it would be nice to support this natively.

- [x] Rename `Artifact` to `Contract`.
- [x] Introduce `struct Artifact`.
- [X] Implement loader for truffle format.
- [x] Implement loader for hardhat export format.
- [x] #196
- [x] #170
- [x] Rework `Builder` to work with `Contract`, implement `ContractBuilder`.
- [x] Support artifact formats in macro.
- [x] Merge and release `ethabi`.
- [x] Merge feature branch into `main`.

### PR DESCRIPTION
**Pull request by taminomara**
Fix #512.

### CODE REVIEW

**Comment by taminomara** [comment]
This branch is rebased onto master. I want to merge it without squashing to preserve history.

**Review by vkgnosis — APPROVED** [review]
Agree that we should merge without squashing. It looks like this is currently disabled for this repository but I think it makes sense in cases like this. Will see if I can enable it in the Github settings.
Edit: enabled it

**Comment by taminomara** [comment]
Used github's rebase button, and now all my commits are listed as 'unverified' 😕
Should've manually pushed to main instead...

**Comment by taminomara** [comment]
Well, no way to fix it now without force-pushing to main 😞

**Comment by taminomara** [comment]
Note: with @nlordell's permission I've fixed commit signatures.

**Pull request merged**
