### PR TITLE
Update edition, dependencies and release new version

### PR DESCRIPTION
**Pull request by vkgnosis**
### Test Plan
CI

### CODE REVIEW

**Comment by vkgnosis** [comment]
Looks like
```
  function multipleResults() public pure returns (uint8, uint8, uint8) {
    return (1, 2, 3);
  }
  function multipleResultsStruct() public pure returns (S memory, S memory) {
    return (S(0, 1), S(2, 3));
  }
```
no longer shows up in the abi. Could be a bug in ethabi.

**Review by nlordell — COMMENTED** [review]
LGTM.

I remember having an `eip-1559` branch that can be merged. Can we include that before releasing a new version? It was dependent on some un-released `web3` code that should now be available.

**Comment by vkgnosis** [comment]
You mean https://github.com/gnosis/ethcontract-rs/pull/638 ? We should wait for an update from @sunce86 to decide that. I will keep this PR as is but won't tag / make a release yet so CI will not create the new version yet.

**Comment by nlordell** [comment]
I mean [this branch](https://github.com/gnosis/ethcontract-rs/tree/eip1559). We currently use it in services because we were waiting for a `web3` crate release with EIP-1559 support.

Specifically it contains this PR: https://github.com/gnosis/ethcontract-rs/pull/646

**Comment by vkgnosis** [comment]
So which PR is supposed to merge that branch? Is it not the one I linked? I'm confused about this situation.
Anyway it seems we can merge this PR and I will hold off on creating the release until we know more about the eip1559 things.

**Comment by nlordell** [comment]
> So which PR is supposed to merge that branch?

I think we need to either:
- Rebase #646 onto `main`
- Or merge #638 into `main` (if it is up to date with what was merged in #646).

Either way, I think you are right that we need to wait for Dusan and we can already merge this (just hold off on releasing).

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
I changed the settings to make the `rust (1.56.1, false, false)` required instead of `rust (1.52.0, false, false)`

**Pull request merged**
