### PR TITLE
Fix ci for beta and nightly rust

### PR DESCRIPTION
**Pull request by e00E**
CI started failing on beta and nightly channels with the clippy warning
option-as-ref-deref with this suggested fix.

### CODE REVIEW

**Comment by e00E** [comment]
This fix is needed for beta and nightly but not allowed for stable. How do we make CI happy?

**Comment by nlordell** [comment]
You have a few options:
- Bump minimum Rust version to 1.40
- `#[allow(clippy::option-as-ref-deref)]`.
- Only enable clippy lints on stable (not on 1.39, beta or nightly).
- Add a shim (`OptionExt` extension trait only for rust version <1.40) (personally not a fan)

**Comment by nlordell** [comment]
Personally I suggest bumping the minimum rust version to 1.40. You will need to update the travis file and the README as well.

**Comment by e00E** [comment]
I have removed the explanatory part of the minimum rust version because there is more than one reason now and it isn't useful to track why this is the minimum version if we are using several normal rust features.

**Review by nlordell — APPROVED** [review]
Ship it!

**Pull request merged**
