### PR TITLE
[Bug] Fix `DynTransport` to no longer wrap itself

### PR DESCRIPTION
**Pull request by nlordell**
Right now, if you create a `DynTransport` from another `DynTransport`, it will be wrapped twice in smart pointer and all futures would be double `Box`-ed. This PR fixes that issue.

### Test Plan

New unit test.

### CODE REVIEW

**Review by e00E — APPROVED** [review]
Looks good but its not really a bug is it? Just an optimization.

**Comment by nlordell** [comment]
Its a bug in that it is not intended and repeatedly creating transports could "leak" memory.

**Review by fleupold — APPROVED** [review]
Saving memory, one pointer at a time...

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FxTiTnqUxyWbsAXq7Ju%2Fgiphy.gif&token=count_money" data-gitmeme-token="count_money"></a>

**Comment by nlordell** [comment]
Right now, if you create a DynTransport from another DynTransport, it will be wrapped twice in smart pointer and all futures would be double Box-ed. This PR fixes that issue.

**Pull request merged**
