### PR TITLE
Clippy Allow too many arguments on generated file.

### PR DESCRIPTION
**Pull request by bh2smith**
As a result of the `BalancerV2WeightedPool` contract we were running into a too many arguments warning:

for 

```
    impl Contract {
        #[doc = "Generated by `ethcontract`"]
        pub fn builder<F, T>(
            web3: &self::ethcontract::web3::api::Web3<T>,
            vault: self::ethcontract::Address,
            name: String,
            symbol: String,
            tokens: Vec<self::ethcontract::Address>,
            normalized_weights: Vec<self::ethcontract::U256>,
            swap_fee_percentage: self::ethcontract::U256,
            pause_window_duration: self::ethcontract::U256,
            buffer_period_duration: self::ethcontract::U256,
            owner: self::ethcontract::Address,
        ) -> self::ethcontract::dyns::DynDeployBuilder<Self>
```

This PR adds `#[allow(clippy::too_many_arguments)]` to the top of just this method although it might be better off at the top of the file as a global thing to ignore. 

Also fixed a few typos.

### CODE REVIEW

**Review by nlordell — APPROVED** [review]
Nice!

**Comment by bh2smith** [comment]
We appear to be failing some CI because of an unrelated issue:

```
 error: failed to parse artifact from source Npm("@gnosis.pm/owl-token@3.1.0/build/contracts/TokenOWL.json")

Caused by:
    0: invalid artifact JSON ''
    1: failed to parse contract artifact JSON: EOF while parsing a value at line 1 column 0
    2: EOF while parsing a value at line 1 column 0
 --> examples/examples/sources.rs:8:24
  |
8 | ethcontract::contract!("npm:@gnosis.pm/owl-token@3.1.0/build/contracts/TokenOWL.json");
  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared type `TokenOWL`
  --> examples/examples/sources.rs:27:20
   |
27 |     let instance = TokenOWL::deployed(&web3)
   |                    ^^^^^^^^ use of undeclared type `TokenOWL`
```

Is this something I should try and fix here?


<details><summary>And also a bunch of other errors on nightly</summary>
error: this expression borrows a reference (`&contract::Context`) that is immediately dereferenced by the compiler
 --> ethcontract-generate/src/contract/deployment.rs:9:36
  |
9 |     let deployed = expand_deployed(&cx);
  |                                    ^^^ help: change this to: `cx`
  |
  = note: `-D clippy::needless-borrow` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&contract::Context`) that is immediately dereferenced by the compiler
  --> ethcontract-generate/src/contract/deployment.rs:11:23
   |
11 |         expand_deploy(&cx).context("error generating contract `deploy` associated function")?;
   |                       ^^^ help: change this to: `cx`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&&str`) that is immediately dereferenced by the compiler
  --> ethcontract-generate/src/contract/deployment.rs:98:48
   |
98 |                 let name_lit = Literal::string(&name);
   |                                                ^^^^^ help: change this to: `name`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::EventParam`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:125:40
    |
125 |             let ty = expand_input_type(&input)?;
    |                                        ^^^^^^ help: change this to: `input`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::EventParam`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:352:32
    |
352 |     let ty = expand_input_type(&param)?;
    |                                ^^^^^^ help: change this to: `param`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::Event`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:410:54
    |
410 |                 let struct_name = expand_struct_name(&event);
    |                                                      ^^^^^^ help: change this to: `event`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::Event`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:437:54
    |
437 |                 let struct_name = expand_struct_name(&event);
    |                                                      ^^^^^^ help: change this to: `event`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&contract::Context`) that is immediately dereferenced by the compiler
  --> ethcontract-generate/src/contract/methods.rs:32:29
   |
32 |             expand_function(&cx, function, aliases.remove(&signature))
   |                             ^^^ help: change this to: `cx`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: aborting due to 8 previous errors

error: could not compile `ethcontract-generate`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: this expression borrows a reference (`&contract::Context`) that is immediately dereferenced by the compiler
 --> ethcontract-generate/src/contract/deployment.rs:9:36
  |
9 |     let deployed = expand_deployed(&cx);
  |                                    ^^^ help: change this to: `cx`
  |
  = note: `-D clippy::needless-borrow` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&contract::Context`) that is immediately dereferenced by the compiler
  --> ethcontract-generate/src/contract/deployment.rs:11:23
   |
11 |         expand_deploy(&cx).context("error generating contract `deploy` associated function")?;
   |                       ^^^ help: change this to: `cx`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&&str`) that is immediately dereferenced by the compiler
  --> ethcontract-generate/src/contract/deployment.rs:98:48
   |
98 |                 let name_lit = Literal::string(&name);
   |                                                ^^^^^ help: change this to: `name`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::EventParam`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:125:40
    |
125 |             let ty = expand_input_type(&input)?;
    |                                        ^^^^^^ help: change this to: `input`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::EventParam`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:352:32
    |
352 |     let ty = expand_input_type(&param)?;
    |                                ^^^^^^ help: change this to: `param`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::Event`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:410:54
    |
410 |                 let struct_name = expand_struct_name(&event);
    |                                                      ^^^^^^ help: change this to: `event`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&ethcontract_common::ethabi::Event`) that is immediately dereferenced by the compiler
   --> ethcontract-generate/src/contract/events.rs:437:54
    |
437 |                 let struct_name = expand_struct_name(&event);
    |                                                      ^^^^^^ help: change this to: `event`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&contract::Context`) that is immediately dereferenced by the compiler
  --> ethcontract-generate/src/contract/methods.rs:32:29
   |
32 |             expand_function(&cx, function, aliases.remove(&signature))
   |                             ^^^ help: change this to: `cx`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: aborting due to 8 previous errors
</details>

**Comment by nlordell** [comment]
> Is this something I should try and fix here?

I restarted the CI. I had issues with `unpkg.com` (what we use for un-packaging npm packges) today that may be related to the error.

**Review by vkgnosis — APPROVED** [review]

**Comment by nlordell** [comment]
@bh2smith It looks like the failure was just an intermittent issue :tada:

**Comment by bh2smith** [comment]
Although it's still failing nightly. I could go through all these issues and fix them, but it doesn't feel like this PR is the correct place for that

**Comment by nlordell** [comment]
> Although it's still failing nightly

Nightly has `allowFailure: true`. Feel free to merge even if the build is failing.

**edit**: Should be fixed in  #527

**Pull request merged**
